### PR TITLE
[WIP] search box

### LINKED ISSUE #26: Main page search box
In ref to #19, #21

I wonder how we can do this. Can we alter the page generation code to have it initially pull in query parameters in the url? Will we have to remove the parameters later?

### PR DESCRIPTION
**Pull request by Chovin**
closes #26 

- [x] express search on query param `q=search_string`
- [ ] advanced search?
- [ ] front-end (@vaniart can you help with this?)

I've added the ability to run a query on page load from url parameters. How should we build out on this feature?

as mentioned in https://github.com/OIT-UOG/specify-webportal-installer/issues/26#issuecomment-474697555 , we have may have a lot of freedom to work with this, maybe have a
- [x] live popup of search results as they type it. 

For now though, let's see if we can get something basic on the front page.

### CODE REVIEW

**Comment by Chovin** [comment]
This branch so far has the express search query string working. You can check the branch out to build the main page search bar out from. @vaniart let me know what else I can do to help with this task!

query

Also, What do you think about surrounding the user's search in wildcards `*seach terms*` by default? 

@burdickdr what are your thoughts on what functionality you'd like to see in the main page search bar? I'm thinking big centered search bar kinda like https://www.gbif.org/ 's

**Comment by Chovin** [comment]
here's some https://www.sitepoint.com/14-jquery-live-search-plugins/ options. SemanticUI and Ajax Live Search look good? /shrug

**Comment by Chovin** [comment]
I've pushed a WIP using the Select2 library. If we go this direction we get a couple more todo items:
- [x] determining which collection to search 
  * drop-down, radio/checkbox, or dropbown multiple-select?
  * or search them all.. not as straight forward as might seem
- [x] making it do something when pressing enter :P
  * where would it go if searching over multiple collections?


search

@vaniart your input and help with the CSS would be greatly appreciated :)
@burdickdr I'd love your input as well in what you'd like this feature to look like/do

**Comment by Chovin** [comment]
Added little select toggle for coral or fish. Thoughts?
@vaniart could I get your help determining best styling/UI/UX?

coral or fish

fyi, there's some html in https://github.com/OIT-UOG/specify-webportal-installer/blob/d5e8709cc4cbe223c6568134deca2b8217c01e10/ROOT/js/search.js#L130-L147

**Comment by Chovin** [comment]
search

I feel like feature-wise this is deployable, we just need a little makeover of it now. @vaniart, when you have time, any help or pointers would be greatly appreciated :)

added:
* selecting an item searches for that name in new tab
* selecting 1st item will search what you're typing in new tab
* search input appears in the new tab (but for some reason if you just press enter on it for the first time instead of typing something, it searches with it empty)
image

**Review by vaniart — DISMISSED** [review]

**Comment by Chovin** [comment]
@vaniart, these changes are good with you? there aren't any style changes you think we should add?

**Review by vaniart — APPROVED** [review]

**Comment by Chovin** [comment]
@burdickdr is ok with pushing this live and doing the style changes later. let's get it live!

**Pull request merged**
